### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by ferenczAndras** [gjerokrsteski/php-captcha-generator#1]
The library shows me all the time that there is no font.
I tried with dir and with url too.
The font do not exists!http://localhost/shop/framework/tools/captcha/arial.ttf
this is what it shows.

**Comment by gjerokrsteski** [comment]
At file `captcha.php`please change code to

```
$captcha = new CaptchaGenerator(
    'arial.ttf',
    'pwdimage.png',
    4
);
```
